---
- name: This is for partition
  hosts: all
  tasks: 
    - name: create 1st partition
      parted: 
             device: /dev/sdb
             number: 1
             part_end: 2GB
             state: present
